blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/anitagraser/movingpandas/discussions
    about: Please ask and answer questions in the MovingPandas Q&A forum.