FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

###################################### user #####################################

ENV SHELL=/bin/bash \
    USER=arg \
    UID=1000 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8

ENV HOME=/home/${USER}

RUN adduser --disabled-password \
    --gecos "Default user" \
    --uid ${UID} \
    ${USER} 

RUN echo "root:root" | chpasswd
RUN echo "${USER}:111111" | chpasswd

###################################### basic tools #####################################

RUN apt-get -o Acquire::ForceIPv4=true update && apt-get -yq dist-upgrade \
    && apt-get -o Acquire::ForceIPv4=true install -yq --no-install-recommends \
    locales \
    make \
    git \
    vim \
    gedit \
    wget \
    sudo \
    lsb-release \
    build-essential \
    net-tools \
    dirmngr \
    gnupg2 \
    mercurial \
    libopencv-dev \
    libcanberra-gtk-module \
    libcanberra-gtk3-module \
    libpcap-dev \
    python3-pip \
    python3-setuptools \
    python3-opencv \
    python3-numpy \
    python3-empy  \
    python3-lxml \
    python3-pymodbus \
    terminator \
    screen \
    nginx \
    openssh-server \
    libglfw3-dev \
    iputils-ping \
    libncurses5-dev \
    libgtk2.0-dev \
    libatk1.0-dev \
    libcairo2-dev \
    libx11-dev \
    libxpm-dev \
    libxt-dev \
    python3-dev \
    pybind11-dev \
    cmake \
    ctags \
    curl \
    g++ \
    cmake \
    xterm \
    libfltk1.3-dev \
    freeglut3-dev \
    libpng-dev \
    libjpeg-dev \
    libxft-dev \
    libxinerama-dev \
    libtiff5-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

##################################### PIP3 ######################################

RUN pip3 install --upgrade pip setuptools

RUN pip3 install \
    gdown \
    pytest \
    flask \
    flask-socketio \
    jupyter \
    virtualenv 

##################################### vim-python-ide ######################################

RUN git clone https://github.com/ARG-NCTU/vim-python-ide.git && \
    cd vim-python-ide && ./install.sh

##################################### MOOS ###########################################

# Add MOOS-IvP to the PATH
ENV PATH "$PATH:${HOME}/pyivp/svn-mirror/bin"

##################################### mini conda######################################

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    chmod +x Miniconda3-latest-Linux-x86_64.sh 

RUN ./Miniconda3-latest-Linux-x86_64.sh -b 

# add conda to path
ENV PATH "$PATH:${HOME}/miniconda3/bin"

# create the environment
RUN echo 1
COPY environment.yml .
RUN conda env create -f environment.yml

# Make RUN commands use the new environment:
RUN echo "source activate" >> ~/.bashrc
RUN echo "conda activate movingpandas" >> ~/.bashrc
SHELL ["/bin/bash", "--login", "-c"]

# conda install nbdev in movingpandas environment
RUN conda install -n movingpandas -c fastai nbdev datasets huggingface_hub  -y

##################################### setting #####################################

RUN echo "${USER} ALL=(ALL)  NOPASSWD: ALL" > /etc/sudoers
# RUN chown -R ${USER}:${USER} ${HOME}/


COPY default /etc/nginx/sites-enabled/default

USER ${USER}

WORKDIR ${HOME}
