 # Top-Level Make Directory for programs through Lab 06                                                    
 # wget http://oceanai.mit.edu/cpplabs/Makefile                                                            

all:
	make -C lib_geometry
	make -C lab05

clean:
	make -C lib_geometry clean
	make -C lab05 clean
